const BASE='https://cross-quadruzz.l-busslerberto.chatgpt.site';const app=document.querySelector('#app');const imageUrls=new Map();let refreshTimer=null;let stopped=false;
document.querySelector('#close').addEventListener('click',()=>{try{const sent=chrome.runtime.sendMessage({type:'quadruzz-close'});if(sent?.catch)sent.catch(()=>{})}catch{/* Context already closed. */}});
window.addEventListener('keydown',event=>{if(event.repeat||event.code!=='KeyW'||!event.altKey||!event.shiftKey||event.ctrlKey||event.metaKey)return;event.preventDefault();event.stopImmediatePropagation();try{const sent=chrome.runtime.sendMessage({type:'quadruzz-toggle'});if(sent?.catch)sent.catch(()=>{})}catch{/* Context already closed. */}},true);
function storageCall(method,value){return new Promise((resolve,reject)=>{try{chrome.storage.local[method](value,result=>{try{const failure=chrome.runtime.lastError;if(failure)reject(new Error(failure.message));else resolve(result)}catch(error){reject(error)}})}catch(error){reject(error)}})}
const storage={get:key=>storageCall('get',key),set:value=>storageCall('set',value),remove:key=>storageCall('remove',key)};
function reportSize(){window.parent.postMessage({type:'quadruzz-resize',height:document.body.scrollHeight},'*')}
function reportReady(){reportSize();window.parent.postMessage({type:'quadruzz-ready'},'*')}
async function api(path){const{token}=await storage.get('token');const response=await fetch(`${BASE}${path}`,{headers:token?{authorization:`Bearer ${token}`}:{}});if(response.status===401)await storage.remove('token');return response}
function signInView(message=''){app.innerHTML=`<div class="connect"><p class="muted">Use your Quadruzz account to continue.</p><button class="primary" id="sign-in">Sign in with ChatGPT</button>${message?`<p class="error">${message}</p>`:''}</div>`;document.querySelector('#sign-in').addEventListener('click',signIn);reportReady()}
async function signIn(){const redirectUrl=chrome.identity.getRedirectURL('quadruzz');try{const callback=await chrome.identity.launchWebAuthFlow({url:`${BASE}/extension/authorize?redirect_uri=${encodeURIComponent(redirectUrl)}`,interactive:true});const token=callback&&new URLSearchParams(new URL(callback).hash.slice(1)).get('token');if(!token)throw new Error();await storage.set({token});try{await chrome.runtime.sendMessage({type:'quadruzz-authenticated'})}catch{/* The next alarm will activate the session. */}await loadMembers()}catch{signInView('Sign-in was not completed.')}}
async function memberImage(member,token){const key=`${member.userId}:${member.imageVersion}`;if(imageUrls.has(key))return imageUrls.get(key);const response=await fetch(`${BASE}/api/extension/profile-image?user=${encodeURIComponent(member.userId)}&v=${member.imageVersion}`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)return'';const url=URL.createObjectURL(await response.blob());imageUrls.set(key,url);return url}
function esc(value){const node=document.createElement('span');node.textContent=value??'';return node.innerHTML}
function stopInvalidContext(error){if(!/extension context invalidated/i.test(String(error)))return false;stopped=true;if(refreshTimer)clearInterval(refreshTimer);return true}
async function loadMembers(){if(stopped)return;try{const{token}=await storage.get('token');if(!token)return signInView();const response=await api('/api/extension');if(response.status===401)return signInView('Please sign in again.');if(!response.ok)throw new Error();const data=await response.json();const images=await Promise.all(data.members.map(member=>memberImage(member,token)));app.innerHTML=`<ul class="members">${data.members.map((member,index)=>`<li class="member${member.extensionActive?'':' inactive'}"><img src="${images[index]}" alt=""><span class="name">${esc(member.displayName)}</span><span class="state">${esc(member.actingState)}</span></li>`).join('')}</ul>`;reportReady()}catch(error){if(stopInvalidContext(error))return;app.innerHTML='<p class="error">Could not reach Quadruzz.</p>';reportReady()}}
new ResizeObserver(reportSize).observe(document.body);try{const started=chrome.runtime.sendMessage({type:'quadruzz-authenticated'});if(started?.catch)started.catch(()=>{})}catch{/* The background alarm will retry. */}void loadMembers();refreshTimer=setInterval(loadMembers,1000);window.addEventListener('unload',()=>{stopped=true;if(refreshTimer)clearInterval(refreshTimer)});
