const BASE='https://cross-quadruzz.l-busslerberto.chatgpt.site';const app=document.querySelector('#app');const imageUrls=new Map();let saving=false;
document.querySelector('#close').addEventListener('click',()=>chrome.runtime.sendMessage({type:'quadruzz-close'}));document.querySelector('#shortcuts').addEventListener('click',()=>chrome.runtime.sendMessage({type:'quadruzz-shortcuts'}));
const storage={get:key=>new Promise(resolve=>chrome.storage.local.get(key,resolve)),set:value=>new Promise(resolve=>chrome.storage.local.set(value,resolve)),remove:key=>new Promise(resolve=>chrome.storage.local.remove(key,resolve))};
async function api(path,init={}){const{token}=await storage.get('token');const response=await fetch(`${BASE}${path}`,{...init,headers:{...(token?{authorization:`Bearer ${token}`}:{}),...(init.body?{'content-type':'application/json'}:{})}});if(response.status===401)await storage.remove('token');return response}
function signInView(message=''){app.innerHTML=`<div class="connect"><p class="muted">Use your Quadruzz account to continue.</p><button class="primary" id="sign-in">Sign in with ChatGPT</button>${message?`<p class="error">${message}</p>`:''}</div>`;document.querySelector('#sign-in').addEventListener('click',signIn)}
async function signIn(){const redirectUrl=chrome.identity.getRedirectURL('quadruzz');try{const callback=await chrome.identity.launchWebAuthFlow({url:`${BASE}/extension/authorize?redirect_uri=${encodeURIComponent(redirectUrl)}`,interactive:true});const token=callback&&new URLSearchParams(new URL(callback).hash.slice(1)).get('token');if(!token)throw new Error();await storage.set({token});await loadMembers()}catch{signInView('Sign-in was not completed.')}}
async function memberImage(member,token){const key=`${member.userId}:${member.imageVersion}`;if(imageUrls.has(key))return imageUrls.get(key);const response=await fetch(`${BASE}/api/extension/profile-image?user=${encodeURIComponent(member.userId)}&v=${member.imageVersion}`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)return'';const url=URL.createObjectURL(await response.blob());imageUrls.set(key,url);return url}
function esc(value){const node=document.createElement('span');node.textContent=value??'';return node.innerHTML}
function attr(value){return esc(value).replaceAll('"','&quot;')}
async function update(fields){if(saving)return;saving=true;try{const response=await api('/api/extension',{method:'POST',body:JSON.stringify(fields)});if(!response.ok)throw new Error();await loadMembers()}catch{app.insertAdjacentHTML('afterbegin','<p class="error">Could not save.</p>')}finally{saving=false}}
function bindOwnRow(){const state=document.querySelector('#own-state');if(state)state.addEventListener('change',()=>update({actingState:state.value}));const form=document.querySelector('#note-form');if(form)form.addEventListener('submit',event=>{event.preventDefault();update({note:document.querySelector('#own-note').value})})}
async function loadMembers(){if(saving||document.activeElement?.id==='own-note')return;const{token}=await storage.get('token');if(!token)return signInView();try{const response=await api('/api/extension');if(response.status===401)return signInView('Please sign in again.');if(!response.ok)throw new Error();const data=await response.json();const images=await Promise.all(data.members.map(member=>memberImage(member,token)));app.innerHTML=`<ul class="members">${data.members.map((member,index)=>{const own=member.userId===data.currentUserId;return `<li class="member"><img src="${images[index]}" alt=""><span class="name">${esc(member.displayName)}${own?' <small class="you">You</small>':''}</span>${own?`<select class="state" id="own-state" aria-label="Acting state"><option value="chat" ${member.actingState==='chat'?'selected':''}>chat</option><option value="ticket" ${member.actingState==='ticket'?'selected':''}>ticket</option></select>`:`<span class="state">${esc(member.actingState)}</span>`}${own?`<form class="note-editor" id="note-form"><input id="own-note" maxlength="280" value="${attr(member.note)}" placeholder="Add note…"><button type="submit">Send</button></form>`:`<span class="note">${member.note?esc(member.note):''}</span>`}</li>`}).join('')}</ul>`;bindOwnRow()}catch{app.innerHTML='<p class="error">Could not reach Quadruzz.</p>'}}
void loadMembers();const refreshTimer=setInterval(loadMembers,1000);window.addEventListener('unload',()=>clearInterval(refreshTimer));
