const BASE='https://cross-quadruzz.l-busslerberto.chatgpt.site';const app=document.querySelector('#app');document.querySelector('#close').addEventListener('click',()=>window.close());
const storage={get:key=>new Promise(resolve=>chrome.storage.local.get(key,resolve)),set:value=>new Promise(resolve=>chrome.storage.local.set(value,resolve)),remove:key=>new Promise(resolve=>chrome.storage.local.remove(key,resolve))};const imageUrls=new Map();
async function api(path,init={}){const{token}=await storage.get('token');const response=await fetch(`${BASE}${path}`,{...init,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})}});if(response.status===401)await storage.remove('token');return response}
function connectView(message=''){app.innerHTML=`<div class="connect"><p class="muted">Connect this browser to your Quadruzz account.</p><button class="link" id="open-site">Get pairing code</button><input id="code" maxlength="8" placeholder="Pairing code"><button class="primary" id="pair">Connect</button>${message?`<p class="error">${message}</p>`:''}</div>`;document.querySelector('#open-site').addEventListener('click',()=>chrome.tabs.create({url:`${BASE}/extension/connect`}));document.querySelector('#pair').addEventListener('click',pair)}
async function pair(){const code=document.querySelector('#code').value.trim().toUpperCase();const response=await api('/api/extension',{method:'POST',body:JSON.stringify({action:'exchange_pairing_code',code})});const data=await response.json();if(!response.ok)return connectView(data.error||'Could not connect.');await storage.set({token:data.token});await loadMembers()}
async function memberImage(member,token){const key=`${member.userId}:${member.imageVersion}`;if(imageUrls.has(key))return imageUrls.get(key);const response=await fetch(`${BASE}/api/extension/profile-image?user=${encodeURIComponent(member.userId)}&v=${member.imageVersion}`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)return'';const url=URL.createObjectURL(await response.blob());imageUrls.set(key,url);return url}
function escapeHtml(value){const node=document.createElement('span');node.textContent=value;return node.innerHTML}
async function loadMembers(){const{token}=await storage.get('token');if(!token)return connectView();try{const response=await api('/api/extension');if(response.status===401)return connectView('Connection expired. Connect again.');if(!response.ok)throw new Error();const data=await response.json();const images=await Promise.all(data.members.map(member=>memberImage(member,token)));app.innerHTML=`<ul class="members">${data.members.map((member,index)=>`<li class="member ${member.online?'online':'offline'}"><img src="${images[index]}" alt=""><span class="name">${escapeHtml(member.displayName)}${member.userId===data.currentUserId?' <small class="you">You</small>':''}</span><span class="status">${member.online?'Online':'Offline'}</span></li>`).join('')}</ul>`}catch{app.innerHTML='<p class="error">Could not reach Quadruzz.</p>'}}
void loadMembers();const refreshTimer=setInterval(loadMembers,1000);window.addEventListener('unload',()=>clearInterval(refreshTimer));
