const BASE='https://cross-quadruzz.l-busslerberto.chatgpt.site';const app=document.querySelector('#app');const imageUrls=new Map();let refreshTimer=null;let stopped=false;
document.querySelector('#close').addEventListener('click',()=>{try{const sent=chrome.runtime.sendMessage({type:'quadruzz-close'});if(sent?.catch)sent.catch(()=>{})}catch{/* Context already closed. */}});
window.addEventListener('keydown',event=>{if(event.repeat||event.code!=='KeyW'||!event.altKey||!event.shiftKey||event.ctrlKey||event.metaKey)return;event.preventDefault();event.stopImmediatePropagation();try{const sent=chrome.runtime.sendMessage({type:'quadruzz-toggle'});if(sent?.catch)sent.catch(()=>{})}catch{/* Context already closed. */}},true);
chrome.runtime.onMessage.addListener(message=>{if(message?.type==='quadruzz-connect-started')connectingView();if(message?.type==='quadruzz-connect-complete')void loadMembers();if(message?.type==='quadruzz-connect-cancelled')signInView()});
function storageCall(method,value){return new Promise((resolve,reject)=>{try{chrome.storage.local[method](value,result=>{try{const failure=chrome.runtime.lastError;if(failure)reject(new Error(failure.message));else resolve(result)}catch(error){reject(error)}})}catch(error){reject(error)}})}
const storage={get:key=>storageCall('get',key),set:value=>storageCall('set',value),remove:key=>storageCall('remove',key)};
function reportSize(){window.parent.postMessage({type:'quadruzz-resize',height:document.body.scrollHeight},'*')}
function reportReady(){reportSize();window.parent.postMessage({type:'quadruzz-ready'},'*')}
async function api(path){const stored=await storage.get(['token','extensionActivitySessionId']);const extensionSessionId=stored.extensionActivitySessionId||crypto.randomUUID();if(!stored.extensionActivitySessionId)await storage.set({extensionActivitySessionId});const separator=path.includes('?')?'&':'?';const response=await fetch(`${BASE}${path}${separator}extension_session=${encodeURIComponent(extensionSessionId)}`,{headers:stored.token?{authorization:`Bearer ${stored.token}`}:{}});if(response.status===401)await storage.remove('token');return response}
async function pulseActivity(){try{const stored=await storage.get(['token','extensionActivitySessionId','extensionActivityPulseAt']);if(!stored.token)return;const now=Date.now();if(now-(stored.extensionActivityPulseAt||0)<15000)return;const extensionSessionId=stored.extensionActivitySessionId||crypto.randomUUID();await storage.set({extensionActivitySessionId,extensionActivityPulseAt:now});const response=await fetch(`${BASE}/api/extension`,{method:'POST',headers:{authorization:`Bearer ${stored.token}`,'content-type':'application/json'},body:JSON.stringify({extensionAction:'heartbeat',extensionSessionId})});if(response.status===401)await storage.remove(['token','extensionActivityPulseAt']);else if(!response.ok)await storage.remove('extensionActivityPulseAt')}catch(error){if(!stopInvalidContext(error))try{await storage.remove('extensionActivityPulseAt')}catch{/* The next member refresh retries. */}}}
function connectingView(){app.innerHTML='<div class="connect"><button class="primary" disabled>Connecting to Cross…</button></div>';reportReady()}
function waitingView(){app.innerHTML='<div class="connect"><button class="primary" id="open-hq">Waiting for approval</button></div>';document.querySelector('#open-hq').addEventListener('click',()=>chrome.runtime.sendMessage({type:'quadruzz-open-hq'}));reportReady()}
function signInView(){app.innerHTML='<div class="connect"><button class="primary" id="sign-in">Connect to Cross</button></div>';document.querySelector('#sign-in').addEventListener('click',signIn);reportReady()}
async function signIn(){connectingView();try{await chrome.runtime.sendMessage({type:'quadruzz-connect'})}catch{signInView()}}
async function connectionPending(){try{return Boolean((await chrome.runtime.sendMessage({type:'quadruzz-connect-state'}))?.connecting)}catch{return false}}
async function memberImage(member,token){const key=`${member.userId}:${member.imageVersion}`;if(imageUrls.has(key))return imageUrls.get(key);const response=await fetch(`${BASE}/api/extension/profile-image?user=${encodeURIComponent(member.userId)}&v=${member.imageVersion}`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)return'';const url=URL.createObjectURL(await response.blob());imageUrls.set(key,url);return url}
function esc(value){const node=document.createElement('span');node.textContent=value??'';return node.innerHTML}
function stopInvalidContext(error){if(!/extension context invalidated/i.test(String(error)))return false;stopped=true;if(refreshTimer)clearInterval(refreshTimer);return true}
async function loadMembers(){if(stopped)return;try{const{token}=await storage.get('token');if(!token){if(await connectionPending())connectingView();else signInView();return}const response=await api('/api/extension');if(response.status===401){if(await connectionPending())connectingView();else signInView();return}if(!response.ok)throw new Error();const data=await response.json();if(data.accessState==='pending'){waitingView();return}if(data.accessState!=='approved'){await storage.remove('token');signInView();return}await pulseActivity();data.members.sort((a,b)=>a.displayName.localeCompare(b.displayName,undefined,{sensitivity:'base'}));const images=await Promise.all(data.members.map(member=>memberImage(member,token)));app.innerHTML=`<ul class="members">${data.members.map((member,index)=>`<li class="member${member.extensionActive?'':' inactive'}"><img src="${images[index]}" alt=""><span class="name">${esc(member.displayName)}</span><span class="state">${esc(member.actingState)}</span></li>`).join('')}</ul>`;reportReady()}catch(error){if(stopInvalidContext(error))return;reportReady()}}
new ResizeObserver(reportSize).observe(document.body);try{const started=chrome.runtime.sendMessage({type:'quadruzz-authenticated'});if(started?.catch)started.catch(()=>{})}catch{/* The background alarm will retry. */}void loadMembers();refreshTimer=setInterval(loadMembers,1000);window.addEventListener('unload',()=>{stopped=true;if(refreshTimer)clearInterval(refreshTimer)});
